version: "3.8"

services:
  zoo1:
    image: zookeeper:3.6.1
    restart: always
    hostname: zoo1
    # https://titangene.github.io/article/networking-in-docker-compose.html
    network_mode: host
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
      - 8080:8080
    volumes:
      - /var/zookeeper/data:/data
      - /var/zookeeper/log:/datalog
    environment:
      ZOO_MY_ID: 1
      # In 3.5 server.id=<address1>:<port1>:<port2>[:role];[<client port address>:]<client port>
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_TICK_TIME: 2000
      ZOO_INIT_LIMIT: 10
      ZOO_SYNC_LIMIT: 5
      ZOO_MAX_CLIENT_CNXNS: 60
    extra_hosts:
      - "zoo1:192.168.166.128"
      - "zoo2:192.168.166.129"
      - "zoo3:192.168.166.130"
---
version: "3.8"

services:
  zoo2:
    image: zookeeper:3.6.1
    restart: always
    hostname: zoo2
    network_mode: host
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
      - 8080:8080
    volumes:
      - /var/zookeeper/data:/data
      - /var/zookeeper/log:/datalog
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_TICK_TIME: 2000
      ZOO_INIT_LIMIT: 10
      ZOO_SYNC_LIMIT: 5
      ZOO_MAX_CLIENT_CNXNS: 60
      # --add-host parameter for docker
    extra_hosts:
      - "zoo1:192.168.166.128"
      - "zoo2:192.168.166.129"
      - "zoo3:192.168.166.130"
---
version: "3.8"

services:
  zoo3:
    image: zookeeper:3.6.1
    restart: always
    hostname: zoo3
    network_mode: host
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
      - 8080:8080
    volumes:
      - /var/zookeeper/data:/data
      - /var/zookeeper/log:/datalog
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
      ZOO_TICK_TIME: 2000
      ZOO_INIT_LIMIT: 10
      ZOO_SYNC_LIMIT: 5
      ZOO_MAX_CLIENT_CNXNS: 60
    extra_hosts:
      - "zoo1:192.168.166.128"
      - "zoo2:192.168.166.129"
      - "zoo3:192.168.166.130"
