version: '2'
services:
  alicloudservice:
    image: alicloudservice
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://alicloudservice-mysql:3306/alicloudservice?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true'
      - 'JHIPSTER_CACHE_REDIS_SERVER=redis://alicloudservice-redis:6379'
      - JHIPSTER_CACHE_REDIS_CLUSTER=false
      - 'SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/auth/realms/jhipster'
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=internal
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=internal
      - JHIPSTER_SLEEP=30
      - SERVER_PORT=80
  alicloudservice-mysql:
    image: 'mysql:8.0.19'
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=alicloudservice
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
  alicloudservice-redis:
    image: 'redis:5.0.7'

  keycloak:
    extends:
      file: keycloak.yml
      service: keycloak
