version: '2'
services:
  sprcloudaliorder-app:
    image: sprcloudaliorder
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://sprcloudaliorder-mysql:3306/sprcloudaliorder?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_CACHE_REDIS_SERVER=redis://sprcloudaliorder-redis:6379
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  sprcloudaliorder-mysql:
    extends:
      file: mysql.yml
      service: sprcloudaliorder-mysql
  sprcloudaliorder-redis:
    extends:
      file: redis.yml
      service: sprcloudaliorder-redis
